import { HeroContentProps } from "../types/HeroContent";

export const dummyHeadlines: string[] = [
  "Transform Your Digital Experience Today",
  "Elevate Your Online Presence with Us",
  "Unlock the Future of Web Design",
  "Craft Your Perfect Digital Story",
  "Revolutionize How You Connect Online",
];

export const dummySubheadlines: string[] = [
  "Our innovative platform gives you the tools to stand out in a crowded digital landscape.",
  "Combining cutting-edge technology with stunning design to create memorable experiences.",
  "Simple, beautiful, and intuitive websites that convert visitors into loyal customers.",
  "We help ambitious brands reach their full potential through strategic design and development.",
  "Create lasting impressions with responsive, accessible, and lightning-fast websites.",
];

export const dummyImages: string[] = [
  "https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&auto=format&fit=crop&w=2072&q=80",
  "https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
  "https://images.unsplash.com/photo-1551434678-e076c223a692?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
  "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=2015&q=80",
  "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80",
];

export const generateRandomContent = (): HeroContentProps => {
  return {
    headline: dummyHeadlines[Math.floor(Math.random() * dummyHeadlines.length)],
    subheadline:
      dummySubheadlines[Math.floor(Math.random() * dummySubheadlines.length)],
    ctaButton: "Get Started", // This remains static as per your code
    image: dummyImages[Math.floor(Math.random() * dummyImages.length)],
  };
};
export const initialContent: HeroContentProps = {
  headline: "Generate text and images with Al",
  subheadline: "Quickly swap in new content generated by Al..",
  ctaButton: "Get Started",
  image: "/images/GraidentAiRobot.jpg",
};
